name: Update copyright year in license file

on:
  schedule:
    - cron: '0 3 1 1 *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v5

      - name: Update license year
        uses: p3lim/license-year-updater@v2
        with:
          files: LICENSE.txt

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update license
          commit-message: Update license
          branch: update-license
          delete-branch: true
